### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by SakerLiu** [lavis-nlp/jerex#1]
When can you release the source code

**Comment by markus-eberts** [comment]
Hi,
the code will be ready for the EACL conference (19-23 April) at the latest. I hope to release it earlier but cannot make any promises for a specific date. If you need our DocRED dataset split for joint training in advance, feel free to write me an email.

**Comment by SakerLiu** [comment]
ohh,tks.


| |
Shandong University
|
|
sakerliujin@163.com
|
签名由网易邮箱大师定制
On 3/9/2021 22:45，Markus Eberts<notifications@github.com> wrote：

Hi,
the code will be ready for the EACL conference (19-23 April) at the latest. I hope to release it earlier but cannot make any promises for a specific date. If you need our DocRED dataset split for joint training in advance, feel free to write me an email.

**Comment by heimaozidew** [comment]
I need it, too. Thank you. 641868693@qq.com

**Comment by heimaozidew** [comment]
I need it, too. Thank you. taopizi1212@163.com

**Comment by markus-eberts** [comment]
I just pushed the code to GitHub (commit 2b47a8cc2500e962dc828e9bcc496f096c783b78).
