### ISSUE TITLE
DocRED dataset

### ISSUE THREAD

**Issue by orilian** [lavis-nlp/jerex#18]
I'm trying to fetch end-to-end (joint) DocRED dataset split. But i can't access it. I don't know if it's my fault, I would appreciate it if you could answer it
![image](https://user-images.githubusercontent.com/73419752/226535924-2861eddc-2291-4907-8c81-dcf2bd123371.png)

**Comment by kantholtz** [comment]
Hi! This is a configuration/migration thing on our end, sorry. I'll let you know when it is working again.

**Comment by kantholtz** [comment]
It should be working again.

**Comment by orilian** [comment]
> It should be working again.

Thank u very much!!
