### ISSUE TITLE
Question regarding "long" documents

### ISSUE THREAD

**Issue by pvcastro** [lavis-nlp/jerex#4]
Hi @markus-eberts ! Congratulations for your work!

I have a question... I was trying to debug your code, and didn't quite find the point in which text sequences longer than 512 tokens are being fed to bert / transformer model. How exactly are you handling this? Where in the code is this?

Thanks!

**Comment by markus-eberts** [comment]
Hi,
the code part you are looking for is in "jerex/models/__init__.py". In the 'create_model' method we increase the embedding matrix of BERT and therefore train the position embeddings of sequences longer than 512 tokens from scratch.

**Comment by pvcastro** [comment]
Thanks!
