### ISSUE TITLE
What's the relation, if there is any relation, between Jerex Model and Spert Model ?

### ISSUE THREAD

**Issue by raphael10-collab** [lavis-nlp/jerex#6]
What's the relation, if there is any relation, between Jerex Model and Spert Model (https://github.com/lavis-nlp/spert) ?

At first sight, they look similar, and may be overlapping. But I guess I'm pretty wrong

**Comment by markus-eberts** [comment]
SpERT and JEREX do indeed overlap to some extend. Both models extract entities (or entity mentions) and relations between them. We also borrowed some ideas from SpERT when we developed JEREX (-> mention representations, localized context, general training regime...).

However, the two models differ in two main aspects: While SpERT detects relations between *mentions* of entities in *sentences*, JEREX extracts relations between *entity clusters* (containing multiple mentions) in whole *documents*. In JEREX, only annotations on an entity(-cluster) level are required (and not between individual mentions as in SpERT). The model than aggregates signals from different parts of the document via multi-instance learning. This way, relations that require reasoning over multiple sentences can be extracted. Document-level and entity(-cluster)-level relation extraction is an active research field and there is still a lot of room for improvement.

Whether SpERT or JEREX is more suited depends on your use case. If you  are interested in more details, feel free to have a look at our papers.
