### ISSUE TITLE
Help ! Annotation tool

### ISSUE THREAD

**Issue by kbrajwani** [lavis-nlp/jerex#8]
Hey , Can you tell me how can i label my dataset and convert into jerex data format? i haven't find annotation tool which is free.

**Comment by markus-eberts** [comment]
Hi, sorry I don't know of any annotation tool to label relations on an entity-level. For the DocRED dataset format see https://github.com/thunlp/DocRED/tree/master/data. I'm closing this issue, since it's not directly related to JEREX.
